name: Redcube Campus
description: Inoffizielle App für die Hochschule München
full_description: 'Diese App ist eine inoffizielle Anwendung für dich als Student oder Studentin der Hochschule München. Sie bietet dir praktische Funktionen, die dein Studium erleichtern und organisieren. Mit dieser App kannst du den Essensplan der Mensa abrufen, ein Dashboard mit Informationen einsehen und Termine sowie den Stundenplan in der Kalenderansicht abrufen. Deine Privatsphäre ist geschützt, da die App keinerlei Tracking oder Analytics verwendet. Hinweis: Diese App ist inoffiziell und steht in keiner Verbindung mit der Hochschule München. Sie wird von Studierenden der Hochschule München ihrer Freizeit entwickelt, die sich über Feedback und Unterstützung freuen.'
android: https://play.google.com/store/apps/details?id=de.moritzhuber.betterHm
iOS: false
web: false
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
  - 6.png
producthunt: false
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
